import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from win32api import GetSystemMetrics


def fluidos(self):
    TextoModelo = QLabel()
    TextoModelo.setPixmap(QPixmap("TextoModelo.png").scaledToHeight(60))
    TextoPBingham = QLabel()
    TextoPBingham.setPixmap(QPixmap("TextoPBingham.png").scaledToHeight(50))
    GraficaBingham = QLabel()
    GraficaBingham.setPixmap(QPixmap("GraficaBingham.png").scaledToHeight(260))
    TextoPotencias = QLabel()
    TextoPotencias.setPixmap(QPixmap("TextoPotencias.png").scaledToHeight(50))
    GraficaPotencias = QLabel()
    GraficaPotencias.setPixmap(QPixmap("GraficaPotencias.png").scaledToHeight(260))
    TextoPotenciasM = QLabel()
    TextoPotenciasM.setPixmap(QPixmap("TextoPotenciasM.png").scaledToHeight(70))
    GraficaPotenciasM = QLabel()
    GraficaPotenciasM.setPixmap(QPixmap("GraficaPotenciasM.png").scaledToHeight(260))
    TextoSmith = QLabel()
    TextoSmith.setPixmap(QPixmap("TextoSmith.png").scaledToHeight(50))
    DibujoSmith = QLabel()
    DibujoSmith.setPixmap(QPixmap("DibujoSmith.png").scaledToHeight(260))
    EasyDrllLogo = QLabel()
    EasyDrllLogo.setPixmap(QPixmap("EasyDrllLogo.png").scaledToHeight(30))
    BtnAceptar = QPushButton("Aceptar")
    BtnAceptar.setFixedHeight(30)
    BtnAceptar.setFixedWidth(100)
    BtnCancelar = QPushButton("Cancelar")
    BtnCancelar.setFixedHeight(30)
    BtnCancelar.setFixedWidth(100)
    BtnRegresar = QPushButton("Regresar")
    BtnRegresar.setFixedHeight(30)
    BtnRegresar.setFixedWidth(100)
    layoutBingham = QVBoxLayout()
    layoutBingham.addWidget(TextoPBingham)
    layoutBingham.addWidget(GraficaBingham)
    layoutPotencias = QVBoxLayout()
    layoutPotencias.addWidget(TextoPotencias)
    layoutPotencias.addWidget(GraficaPotencias)
    layoutPotenciasM = QVBoxLayout()
    layoutPotenciasM.addWidget(TextoPotenciasM)
    layoutPotenciasM.addWidget(GraficaPotenciasM)
    layoutSmith = QVBoxLayout()
    layoutSmith.addWidget(TextoSmith, Qt. StretchTile, Qt.AlignCenter)
    layoutSmith.addWidget(DibujoSmith)
    layoutBtn = QHBoxLayout()
    layoutBtn.addWidget(BtnAceptar, Qt. StretchTile, Qt.AlignRight)
    layoutBtn.addWidget(BtnCancelar)
    layoutBtn.addWidget(BtnRegresar)
    layoutConjunto = QHBoxLayout()
    layoutConjunto.addLayout(layoutBingham)
    layoutConjunto.addLayout(layoutPotencias)
    layoutConjunto.addLayout(layoutPotenciasM)
    layoutConjunto.addLayout(layoutSmith)
    layoutPantalla = QVBoxLayout()
    layoutPantalla.addWidget(EasyDrllLogo, Qt.StretchTile, Qt.AlignRight)
    layoutPantalla.addWidget(TextoModelo, Qt.AlignLeft)
    layoutPantalla.addStretch()
    layoutPantalla.addLayout(layoutConjunto)
    layoutPantalla.addSpacing(70)
    layoutPantalla.addLayout(layoutBtn)
    layoutPantalla.addSpacing(20)
    central_widget = QWidget()
    central_widget.setLayout(layoutPantalla)
    self.setCentralWidget(central_widget)
